name: Build Runner Check

on:
  pull_request:
    branches:
      - develop

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: git diff --exit-code